;;; Automatically generated by ‘recentf’ on Fri Jun 10 10:11:59 2022.

(setq recentf-list
      '(
        "/home/pedro/.repos-git/dotfiles/.config/fish/config.fish"
        "/home/pedro/.repos-git/ppfetch/src/main.c"
        "/home/pedro/.repos-git/studying-programming/C-lang/do-basico-ao-avancado/exercicios-sec3/ex08.c"
        "/home/pedro/.repos-git/studying-programming/C-lang/do-basico-ao-avancado/exercicios-sec3/ex07.c"
        "/home/pedro/.repos-git/studying-programming/C-lang/do-basico-ao-avancado/exercicios-sec3/ex06.c"
        "/home/pedro/.repos-git/studying-programming/C-lang/do-basico-ao-avancado/exercicios-sec3/ex05.c"
        "/home/pedro/.repos-git/studying-programming/C-lang/do-basico-ao-avancado/exercicios-sec3/ex04.c"
        "/home/pedro/.repos-git/studying-programming/C-lang/do-basico-ao-avancado/exercicios-sec3/ex03-2.c"
        "/home/pedro/.repos-git/dotfiles/emacs.d/init.el"
        "/home/pedro/.emacs.d/init.el"
        "/home/pedro/.repos-git/studying-programming/C-lang/do-basico-ao-avancado/exercicios-sec3/ex03-1.c"
        "/home/pedro/.repos-git/studying-programming/C-lang/do-basico-ao-avancado/exercicios-sec3/ex03.c"
        "/home/pedro/.repos-git/studying-programming/C-lang/do-basico-ao-avancado/exercicios-sec3/ex02.c"
        "/home/pedro/.repos-git/studying-programming/C-lang/do-basico-ao-avancado/exercicios-sec3/ex01.c"
        "/home/pedro/.repos-git/studying-programming/C-lang/do-basico-ao-avancado/avulsos/programa1.c"
        "/home/pedro/.repos-git/studying-programming/rust/rust book/guessing_game/src/main.rs"
        "/home/pedro/.repos-git/studying-programming/python/CursoEmVideo/desafio036.py"
        "/home/pedro/.repos-git/studying-programming/C-lang/introducao-a-programacao-com-c/media-de-dois-numeros.c"
        ))

(setq recentf-filter-changer-current 'nil)


;; Local Variables:
;; coding: utf-8-emacs
;; End:
